### ISSUE TITLE
Document in spec that github issues can be used

### ISSUE THREAD

**Issue by scheib** [WebBluetoothCG/web-bluetooth#103]
Current spec text reads:

>  Changes to this document may be tracked at https://github.com/WebBluetoothCG/web-bluetooth/commits/gh-pages.
>
>  If you wish to make comments regarding this document, please send them to public-web-bluetooth@w3.org (subscribe, archives).

Perhaps it should include

>  Changes to this document may be tracked at https://github.com/WebBluetoothCG/web-bluetooth/commits/gh-pages.
>
>  If you wish to make comments regarding this document, please [__file issues__](https://github.com/WebBluetoothCG/web-bluetooth/issues) or write to public-web-bluetooth@w3.org (subscribe, archives).

**Comment by jyasskin** [comment]
This comes from the ReSpec boilerplate, and Marcos filed it as w3c/respec#416.

I'm going to close the issue in this repo, but whenever ReSpec grows github support, we should be sure to use it here.
