### ISSUE TITLE
Should BluetoothDevice.uuids be filtered?

### ISSUE THREAD

**Issue by scheib** [WebBluetoothCG/web-bluetooth#104]
For privacy reasons, should the list of uuids on the BluetoothDevice be filtered to the set of services matched by BluetoothScanFilter and RequestDeviceOptions.services?

E.g. if a web page requests a device that offers a heart rate service, optionally with access to battery level, should it be able to discover that OBEXObjectPush is also supported on a device, providing more data about the device than may be necessary?

**Comment by jyasskin** [comment]
It is filtered. See step 15 under https://webbluetoothcg.github.io/web-bluetooth/#dfn-get-the-bluetoothdevice-representing.
