### ISSUE TITLE
Describe what happens in response to disconnection (a lost ATT Bearer)

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#114]
https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothdevice-gattserver describes `BluetoothDevice.gattServer` becoming `null`, and [`BluetoothGATTRemoteServer.connected`](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothgattremoteserver-connected) needs to become false.

I'm not certain that `BluetoothDevice.gattServer` should actually become null after the first connection, and if it does then maybe it should go back to the original object on reconnection?

**Comment by beaufortfrancois** [comment]
I agree with you it shouldn't become `null`. The `connected` set to `false` should be enough especially if we add connect/disconnect Bluetooth events (https://github.com/WebBluetoothCG/web-bluetooth/issues/194)
