### ISSUE TITLE
Describe what happens when an advertising packet is received.

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#117]
We need to at least update [`BluetoothDevice.adData`](http://webbluetoothcg.github.io/web-bluetooth/#idl-def-bluetoothdevice-addata).

**Comment by jyasskin** [comment]
And fire an event.

**Comment by beaufortfrancois** [comment]
Shall we have a label for all things related to Physical Web?

**Comment by beaufortfrancois** [comment]
A related discussion happens at https://code.google.com/p/chromium/issues/detail?id=568137
