### ISSUE TITLE
What happens if getPrimaryService can't find the service.

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/web-bluetooth#118]

**Comment by jyasskin** [comment]
From https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothgattremoteserver-getprimaryservice, "returns null if its argument is empty [i.e. no service is found]". If the name of the service was bad, https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothuuid-getservice throws a `SyntaxError`.

**Comment by g-ortuno** [comment]
ah you're right sorry!
