### ISSUE TITLE
[Feature Request] Link button in IDL definitions

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/web-bluetooth#120]
Is there anyway we can add link buttons to IDL definitions to get the url to the IDL faster? Every time I want to reference the IDL I'm looking at, I have to open the inspector copy the id and paste it into the address bar.

**Comment by jyasskin** [comment]
I use https://chrome.google.com/webstore/detail/link-to-here/fhpigohjannbboeplbkfdkojklnjiknh, but this would make a reasonable feature in https://github.com/w3c/respec. We won't do it in just this one spec.

**Comment by jyasskin** [comment]
I could switch on https://www.w3.org/respec/ref.html#includepermalinks though.

**Comment by jyasskin** [comment]
It still may be worth filing a bug against ReSpec to link the IDL better.
