### ISSUE TITLE
nit: Related object is in a different position every time

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/web-bluetooth#122]
This is probably bike shedding but sometimes the related object is the first member of the object other times is the last member before the functions and sometimes is in the middle. For example [BluetoothGATTRemoteServer](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothgattremoteserver) has its `device` member at the top, [BluetoothGATTService](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothgattservice) has its `device` member at the bottom, and [BluetoothGATTCharacteristic](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothgattcharacteristic) has its `service` member in the middle. Have you thought about always putting them before the object's functions?

**Comment by jyasskin** [comment]
Good catch. 2 of these were blindly copied from https://developer.chrome.com/apps/bluetoothLowEnergy#type-Service. I'd lean toward always putting the parent first.
