### ISSUE TITLE
Fix "ID" capitalization

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#139]
In https://github.com/w3c/web-nfc/issues/27#issuecomment-122013007 @domenic says "Id" should only have an initial capital. @annevk points out in https://github.com/jyasskin/web-bluetooth-1/commit/8154c44f9857336bb5f1d93a0aadfa3a1c19dc12#commitcomment-12208486 that I changed it the other way. https://github.com/w3ctag/design-principles/issues/15 doesn't have explicit guidance for this yet. We could avoid this by just giving `BluetoothDevice`s "id"s instead of "instanceId/D"s.

**Comment by domenic** [comment]
> We could avoid this by just giving BluetoothDevices "id"s instead of "instanceId/D"s.

Unless "instance id" is a term of art, this sounds like a nice simplification :)

Otherwise, I can try to do some more serious research to make sure I am correct about the platform preferring `Id` to `ID`.

**Comment by g-ortuno** [comment]
what about vendorIDSource, vendorID and productID?

**Comment by domenic** [comment]
Results:

- NonElementParentNode's getElementById
- TextTrackList's getTrackById
- TextTrackCueList's getCueById
- VTTRegionList's getRegionById
- RTCPeerConnection's getStreamById
- HTMLMediaElementAudioOutputDevice's setSinkId
- DocumentType's publicId and systemId
- MediaKeyEvent's sessionId
- PointerEvent's pointerId
- MessageEvent's lastEventId

There are a few capital "ID"s, on navigator in particular. But the trend is clear. I will update https://w3ctag.github.io/design-principles/#casing-rules to call out "Id" explicitly.
