### ISSUE TITLE
Read and Write not permitted don't exist anymore

### ISSUE THREAD

**Issue by beaufortfrancois** [WebBluetoothCG/web-bluetooth#156]
Based on https://codereview.chromium.org/1307153002, we may want to merge "Read Not Permitted" and "Write Not Permitted" into a simple "Not Permitted" error in https://webbluetoothcg.github.io/web-bluetooth/#error-handling

**Comment by jyasskin** [comment]
"Read Not Permitted" and "Write Not Permitted" are errors from the Bluetooth standard, in section 3.F.3.4.1.1. It's good that they map to the same JavaScript error, since ChromeOS doesn't distinguish them, but the keys in that table were never meant to match what particular platforms report.
