### ISSUE TITLE
Should GetGATTChildren required connected == true?

### ISSUE THREAD

**Issue by scheib** [WebBluetoothCG/web-bluetooth#171]
getPrimaryService and other methods rely on GetGATTChildren algorithm to obtain GATT objects. Should they fail if not connected?

The Chromium implementation currently attempts to obtain this information even when not connected. It could be cached, so it is possible to allow implementations to attempt to service these requests, but it would be cleaner to specify either that they must attempt cached results or reject with a known error.

**Comment by jyasskin** [comment]
Probably yes. This is also related to #114. I think we have several holes around handling disconnected devices.

**Comment by jyasskin** [comment]
I think I'd rather fail fast on a disconnected device, probably with a `NetworkError`, rather than allowing cached results.

**Comment by g-ortuno** [comment]
This seems like something that should be added to the [Populate Cache Algorithm](https://webbluetoothcg.github.io/web-bluetooth/#populate-the-bluetooth-cache). Something like: If device.connected == false then return a Network Error.
