### ISSUE TITLE
Unconditionally define the gattServer attribute, and move connect() there

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#181]
Talking with @yrliou and @brucesunmozilla at TPAC, it looks like moving connect into BluetoothGATTRemoteServer makes more sense than the current arrangement.

**Comment by beaufortfrancois** [comment]
To be clear, does that mean we would have something like this?

```js
navigator.bluetooth.requestDevice({filters:[{services:['battery_service']}]})
.then(device => device.gattServer.connect())
.then(gattServer => {
  // Is gattServer returned?
  // Are device.gattServer and gattServer the same?
})

**Comment by jyasskin** [comment]
Yes, yes, and yes, respectively. We could also provide device.connectGATT() as an alias for device.gattServer.connect(), if folks think that's useful.

**Comment by beaufortfrancois** [comment]
I like it without the alias.

**Comment by yrliou** [comment]
We proposed this since it looks more symmetric in this way, it's a bit of weird that connect and disconnect functions are at different levels.
Personally I would vote for no connectGatt alias.
