### ISSUE TITLE
Remove BluetoothDevice.paired

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#189]
It looks like CoreBluetooth has no way to get this information, so we can't expose it universally. It's a holdover from `chrome.bluetooth`.

**Comment by beaufortfrancois** [comment]
Work in progress at https://codereview.chromium.org/1564953003/

**Comment by beaufortfrancois** [comment]
https://codereview.chromium.org/1564953003/ has landed.
