### ISSUE TITLE
Add connect and disconnect gatt server Bluetooth events.

### ISSUE THREAD

**Issue by beaufortfrancois** [WebBluetoothCG/web-bluetooth#194]
The same way, WebUSB added `connect` and `disconnect` events (https://github.com/reillyeon/webusb/commit/5806adfc523ff5146bc9fa883367b024d1d62699), it would be nice to have them in WebBluetooth so that Web Apps can detect connected/disconnected devices.

Just some ideas there there...
```js
navigator.bluetooth.addEventListener('connectGatt', handleGattServer);
navigator.bluetooth.addEventListener('disconnectGatt', handleGattServer);

function handleGattServer(event) {
  var gattServer = target.value;
  console.log('Gatt Server connected: ', gattServer.connected);
}
```

or 

```js
navigator.bluetooth.requestDevice({filters:[{services:['battery_service']}]})
.then(device => device.connectGatt())
.then(gattServer => {
  gattServer.addEventListener('disconnect', handleGattServer);
  // Not sure about the use of "connect" there...
  gattServer.addEventListener('connect', handleGattServer);
});

function handleGattServer(event) {
  var gattServer = target.value;
  console.log('Gatt Server connected: ', gattServer.connected);
}

**Comment by beaufortfrancois** [comment]
Same as #159 
Sorry for duplicating issues....

**Comment by jyasskin** [comment]
I'm initially inclined not to fire a 'connected' event when `gattServer.connect()` returns. Is there a reason we need it? (Obviously we need 'disconnected' since the page has no other way to discover that happened.)

**Comment by beaufortfrancois** [comment]
I was thinking we could use for a "reconnect" scenario after a disconnect happened but... I'm not sure either we need it ;)

**Comment by jyasskin** [comment]
Oh, right, I forgot auto-connection. Let's handle that by having `connect()` hang until a connection is made, with `disconnect()` being the way to cancel it. So, further discussion on #152. And #159 or #114 will handle the `disconnected` event.
