### ISSUE TITLE
Connect to multiple BLE devices from web app?

### ISSUE THREAD

**Issue by ketile** [WebBluetoothCG/web-bluetooth#195]
Quick question: Will it be possible to connect to more than one BLE peripheral at a time from a single tab or web app?

**Comment by beaufortfrancois** [comment]
Yes! Have a look at https://github.com/WebBluetoothCG/web-bluetooth/issues/42

**Comment by beaufortfrancois** [comment]
Feel free to add some comments on #42 ;)

**Comment by ketile** [comment]
Thanks!
