### ISSUE TITLE
Should `requestDevice` automatically connect to the device?

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#2]
Discovery and connection are separate steps in the Bluetooth spec and in most APIs that access Bluetooth. However, these APIs generally don't expose as compressed a discovery flow as this one, nor do they involve an "open-like" dialog where the user selects a device.

I don't know of a use for getting a handle to an un-connected device, but if you know of one please mention it here.

If there's a use, we need to expose that possibility. It's not clear whether we should expose it by having `requestDevice()` return an un-connected device regardless and making all developers call `connect()` explicitly, or by having `requestDevice()` default to returning a connected device, but with an option to override that default.

**Comment by alainmanigat** [comment]
Hello eveyryone,
I am beginner by using web api bluetooth.
Can someone please, confirm if it's possible to target a protected characteristic and have some example?
It's very urgent.
Best Regards,

**Comment by scheib** [comment]
@alainmanigat Asking this question is best done on https://stackoverflow.com/questions/tagged/web-bluetooth.  Replying to an unrelated closed spec issue isn't a good method.
