### ISSUE TITLE
startNotifications should always write descriptor if device is not bonded

### ISSUE THREAD

**Issue by beaufortfrancois** [WebBluetoothCG/web-bluetooth#220]
If devices are not bonded, notifications won't be remembered after a disconnection.

Therefore, instead of giving the responsibility the check whether devices are bonded or not to the UA, I suggest `startNotifications()` should always write descriptor no matter what.

Same applies to `stopNotifications()` of course.

WDYT?

Background: https://bugs.chromium.org/p/chromium/issues/detail?id=589796#c9

**Comment by mjdietzx** [comment]
I think this is necessary as well. I have a use case for this where we are doing a firmware transfer over the air, the link is lost for some reason, and the first thing we need to do is re enable notifications on a characteristic before starting the transfer where we left off.

Whether we always write the descriptor no matter what, or we actually read it and only write it if it is not enabled is up to you (i can't think of any problems with either way but the second seems a bit cleaner).

**Comment by g-ortuno** [comment]
@jyasskin: I looked at this a bit closer. We should be clearing the [`active notification context set`](https://webbluetoothcg.github.io/web-bluetooth/#active-notification-context-set) upon disconnection.

**Comment by jyasskin** [comment]
There are some characteristics (Service Changed comes to mind, although it's not user-visible) that queue up information to send to bonded devices, and then dump it out on re-connection. If we make sites re-register for notifications/indications on re-connection, they'll generally miss that set of notifications. @Vudentz also makes that point at the bottom of http://permalink.gmane.org/gmane.linux.bluez.kernel/66966. That said, it's going to be a fair amount of bookkeeping in the UA to keep the queue of notifications that a site hasn't seen. Maybe we should make them re-retrieve the data.

The spec definitely should say that non-bonded devices clear their notification set on disconnection.

**Comment by beaufortfrancois** [comment]
What should we do then?

**Comment by g-ortuno** [comment]
For the non bonded case we just have to wait for @jyasskin to fix the spec.
