### ISSUE TITLE
After gatt.connect() server coming back undefined.

### ISSUE THREAD

**Issue by danhklein** [WebBluetoothCG/web-bluetooth#232]
After .requestDevice, I'm unable to get server out of next promise. Would love advice about what is happening. Thanks in advance!

navigator.bluetooth.requestDevice({
              filters: [{
                namePrefix: ['BB']
              }]
            })
            .then(device => {
           //I am getting device object here
     
             return  device.gatt.connect();
        })
        .then(server => {
        //server coming back undefined.
           server.getPrimaryService("22bb746f-2bb0-7554-2d6f-726568705327");
        })

**Comment by g-ortuno** [comment]
Thanks for reaching out! In the future please file any issues regarding the implementation in [crbug.com/](https://bugs.chromium.org/p/chromium/issues/entry). I've opened [crbug.com/606988](http://crbug.com/606988) for you and included a couple of questions there so we can figure out the problem.

**Comment by beaufortfrancois** [comment]
@danhklein Did you see a picker like one below?
<img src="https://developers.google.com/web/updates/images/2015-07-22-interact-with-ble-devices-on-the-web/bluetooth-device-chooser.png">
