### ISSUE TITLE
Blacklisting various services, characteristics, and descriptors.

### ISSUE THREAD

**Issue by armansito** [WebBluetoothCG/web-bluetooth#24]
The reason for having the BluetoothGattCharacteristic.startNotifications|stopNotifications methods in the first place is to prevent apps from directly writing to the Client Characteristic Configuration (CCC below) descriptor (which is used to enable/disable notifications and indications from the characteristic). This raises the following two points:

- BluetoothGattDescriptor.writeValue should NOT allow writing to the CCC descriptor directly to prevent one application from disabling notifications/indications while another application is interested in them. Either that or the (CCC) descriptor perhaps shouldn't ever be exposed.
- It should be made clear to the implementation side that startNotifications and stopNotifications internally needs to keep a reference count of notification "sessions" of sort to manage the value of the CCC descriptor.

**Comment by jyasskin** [comment]
We probably need to have an updatable list of blacklisted things, to handle new manufacturers that allocate UUIDs that have security problems if they're accessed from the web. I'm in the process of sending a New Work Proposal to the BT SIG to have them maintain a list like this, but until that winds its way through the process, @slightlyoff suggested we pick a quick-and-dirty location for the registry.

How about a new git repository named something like https://github.com/WebBluetoothCG/registries with a text file in it for each blacklist? We can hand that list over to a more official place whenever we pick the right official place.

**Comment by ariccio** [comment]
I don't know that it's fair to say "the GAP and GATT GATT services (that is GATT services with 0x1800 and 0x1801) shouldn't ever be accessed by the application. "...
I run a citizen-science CO2 tracking app that's used as a volunteer part of the coronavirus response, and I'd like to be able to read the aranet4 serial number over bluetooth. Users have an awful lot of trouble entering it correctly as is, and this would also help automated data collection. 

In that light, I also don't think it's compatible with the idea that ["Blocklisting UUIDs used on only vulnerable devices is preferred"](https://github.com/WebBluetoothCG/registries/issues/2#issuecomment-1000950490). Does that make sense?

**Comment by ariccio** [comment]
Hmm. I'm seeing another issue that makes the serial # blacklisting more of a problem. 

Basically, I'd like to tie a specific device-via-bluetooth to a specific instance of that device in my database. If users only have a *single* aranet4, this can work ok. But if they have multiple, how do I know programmatically which bluetooth device they've connected to? As their calibrations may be drifting differently (they probably will), this is a data-integrity problem. 

I just went ahead and looked into the `id` `BluetoothDevice` field, and I'm seeing that the way that it's implemented in google chrome is not at all repeatable. It's generated at runtime with a `crypto::RandBytes(bytes);` call! This is not repeatable or reliable. So how else can I make use of WebBluetooth?

Honestly, it's looking more and more like I'll be spinning up a react native app.

**Comment by scheib** [comment]
We plan to offer stable IDs for devices via getDevices()
https://chromestatus.com/feature/4797798639730688

However, that project has not completed yet and is currently paused as
people work on higher priority items.
