### ISSUE TITLE
How to add disconnect event handler

### ISSUE THREAD

**Issue by aircable** [WebBluetoothCG/web-bluetooth#244]
I would like to get a disconnect event from the gatt server.

            navigator.bluetooth.requestDevice(options)
                .then(function ( device ) {
                    console.log('Name: ' + device.name);
                    server.addEventListener( 'gattserverdisconnected', handleDisconnect );
                    return device.gatt.connect();
                })
                .then(function ( server ) {
                    console.log('server ' + server );
                    return server.getPrimaryService( MESH_SERVICE_UUID );
                })

The event listener add is accepted, but never executed. The BluetoothRemoteGATTServer object does not have a addEventListener function.
Am I doing something wrong? This is on Android Chrome 51.0.2704.81
Thanks

**Comment by beaufortfrancois** [comment]
As shown in https://googlechrome.github.io/samples/web-bluetooth/device-disconnect.html, the `gattserverdisconnected` event must be registered on the BluetoothDevice, not the server.

**Comment by beaufortfrancois** [comment]
In your code, here's how it should look like:

```js
        navigator.bluetooth.requestDevice(options)
            .then(function ( device ) {
                console.log('Name: ' + device.name);
                device.addEventListener( 'gattserverdisconnected', handleDisconnect );
                return device.gatt.connect();
            })
            .then(function ( server ) {
                console.log('server ' + server );
                return server.getPrimaryService( MESH_SERVICE_UUID );
            })

**Comment by aircable** [comment]
yes, sorry, that was a typo. I tried that and forgot to change it back.
this threw an error of course.

device.addEventListener is not being called. That was my error report.

**Comment by g-ortuno** [comment]
As you can see from the [Implementation Status](https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md), the disconnection event was added in m52. I recommend you download [Chrome Dev](https://play.google.com/store/apps/details?id=com.chrome.dev&hl=en) to try it out.

**Comment by aircable** [comment]
that explains it, thanks, will report

**Comment by aircable** [comment]
closed, it does work, on Chrome DEV
Thanks
