### ISSUE TITLE
Characteristic's WriteValue function should check the value of the Write property

### ISSUE THREAD

**Issue by zakorgy** [WebBluetoothCG/web-bluetooth#247]
Similar to `ReadValue` function https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattcharacteristic-readvalue (Step 4.1), I think we should check the related `Write` property in a substep in `WriteValue` https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattcharacteristic-writevalue (Step 6), and if not set, reject promise with a NotSupportedError.

**Comment by jyasskin** [comment]
You're absolutely correct.
