### ISSUE TITLE
Translationg the documents is allowed? 

### ISSUE THREAD

**Issue by tkybpp** [WebBluetoothCG/web-bluetooth#259]
I've been translating the [specification](https://webbluetoothcg.github.io/web-bluetooth/) to [Japanese](https://tkybpp.github.io/web-bluetooth-jp/) one.
I want to promote it for developers in Japan, but, in the first place, is translating allowed as a reference(not official)? 
Of course I append some cautions that this is not official and you have to check official documents to know the latest and correct contents because this is just a reference so my translate not guarantee that.

**Comment by jyasskin** [comment]
Yes, translations are great. Thank you!
