### ISSUE TITLE
How to handle changing advertised UUIDs

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/web-bluetooth#290]
Step 8 of [get the BluetoothDevice representing](https://webbluetoothcg.github.io/web-bluetooth/#get-the-bluetoothdevice-representing)  states:
> 8. Add device’s advertised Service UUIDs to result.[[unfilteredUuids]].

But it isn't clear what advertised Service UUIDs means when a device is alternating UUIDs. Is it only the last Advertised UUIDs? All the UUIDs we've seen during that particular scan or all the UUIDs we've seen so far across scans?

Given that only BlueZ caches the advertised UUIDs I think this should be specified.

**Comment by beaufortfrancois** [comment]
Background at https://bugs.chromium.org/p/chromium/issues/detail?id=645023

**Comment by jyasskin** [comment]
Which do you think is the right set of UUIDs? The field should probably converge on the discovered set of UUIDs that are actually in the GATT server, but for its initial value, maybe it should be the UUIDs the UA has seen "recently", where we leave "recently" up to the UA?

**Comment by jyasskin** [comment]
Or should we remove `uuids` entirely, and have people call `getPrimaryServices()` instead?

**Comment by beaufortfrancois** [comment]
I actually thought about that yesterday and didn't see the value of keeping `uuids` when we get them with `getPrimaryServices`. I'd vote for removing them.

**Comment by beaufortfrancois** [comment]
I can't find the chromium bug for removing BluetoothDevice uuids. I think it should be a `ship blocking` issue. WDYT?

**Comment by scheib** [comment]
Chromium issue [Remove BluetoothDevice.uuids attribute.](https://bugs.chromium.org/p/chromium/issues/detail?id=653317) filed.
