### ISSUE TITLE
Support for requesting devices with specific service data in adv packets

### ISSUE THREAD

**Issue by irgu** [WebBluetoothCG/web-bluetooth#294]
Is there any plan to add filtering by specific service data? I mean something like bit mask filter for requesting devices with specific pattern inside the service data.

**Comment by beaufortfrancois** [comment]
Current implementation for filtering service data and manufacturer data is pretty simple. However, we've talked about adding masks as you can read at https://github.com/WebBluetoothCG/web-bluetooth/issues/153#issuecomment-134648172

May I ask what is your use case?

**Comment by irgu** [comment]
Mentioned comment perfectly applies to what I'm looking for. In my case I have proprietary application level packets encapsulated in service data.

**Comment by beaufortfrancois** [comment]
@jyasskin Should we add masks to the spec now then?

**Comment by beaufortfrancois** [comment]
@irgu Feel free to comment on https://github.com/WebBluetoothCG/web-bluetooth/pull/297

**Comment by beaufortfrancois** [comment]
@irgu Is this still something you're interested in?
