### ISSUE TITLE
Specify how re-connection works

### ISSUE THREAD

**Issue by shuangMoz** [WebBluetoothCG/web-bluetooth#31]
Currently `connect()` is missing auto-connect optional parameter. Do we have any concern to do this? Without auto-connect parameter, I think it will be hard to handle reconnection scenario.  If a website already paired and connect with a Smart Device, Smart Device moves out-of-range. Is it nature to reconnect smart device if the user already trusted this website to connect with that specific device?

**Comment by wesleyyee** [comment]
Is there any update on this?

**Comment by adhodi** [comment]
is there a way to get connected device after page load yet?

**Comment by reillyeon** [comment]
@adhodi I've answered this on #428. This issue and persistent permissions are interrelated problems as once permission can be maintained across multiple page loads it is also much more likely that a device will have gone in and out of range.

**Comment by reillyeon** [comment]
Discussed at the 2019 TPAC F2F. The combination of the `watchAdvertisements()` and `connect()` methods are sufficient to determine that a device is in range and connectable and to connect to it. As mentioned previously Chromium does not currently implement these methods but the mechanism is specified.

```js
device.addEventListener('gattserverdisconnected', async e => {
  await device.watchAdvertisements();
});
device.addEventListener('advertisementreceived', async e => {
  try {
    await device.gatt.connect();
    await device.unwatchAdvertisements();
  } catch (e) {
    // Continue listening for advertisements.
  }
});

**Comment by Emill** [comment]
Well it would be much better to use the OS's auto-connect feature if available. That leads to a much faster connection setup.
Also with Android's scan parameters when not full duty is used, it can take very long time to discover the device.
