### ISSUE TITLE
Rename Blacklist to something non offensive. 

### ISSUE THREAD

**Issue by scheib** [WebBluetoothCG/web-bluetooth#327]
TAG review included a request to avoid 'blacklist' as it can be offensive. https://github.com/w3ctag/spec-reviews/issues/139#issuecomment-257509432 

https://en.wikipedia.org/wiki/Blacklist_(computing) includes related terms 'Block list', and 'access control'.

Some initial alternative ideas:
- Access Control List
- Block List
- Exclude List

**Comment by domenic** [comment]
We switched all uses of blacklist/whitelist to blocklist/safelist in HTML, FWIW.

**Comment by beaufortfrancois** [comment]
I'd vote for blocklist.

**Comment by beaufortfrancois** [comment]
And here are two patches: https://github.com/WebBluetoothCG/registries/pull/18 and https://github.com/WebBluetoothCG/web-bluetooth/pull/329
