### ISSUE TITLE
Battery demo - connection hanging on Mac, failing on Android

### ISSUE THREAD

**Issue by poshaughnessy** [WebBluetoothCG/web-bluetooth#337]
Hi, I'm trying to get the basic battery service reading demo working, but I'm not getting past device.gatt.connect().

Using the demo here: https://googlechrome.github.io/samples/web-bluetooth/battery-level.html, on Chrome desktop on Mac (stable and Canary), I get the following output:

```
Requesting Bluetooth Device...
Connecting to GATT Server...
```

Then it hangs.

The peripheral I'm trying to connect to is the bleno battery-service example running on my Ubuntu machine.

On Android (S7 Edge, Android 6.0.1) it also fails, but it gives an error message:

```
Requesting Bluetooth Device...
Connecting to GATT Server...
Argh! NetworkError: Connection failed for unknown reason.
```

No indication of any issues with the peripheral from the terminal output on Ubuntu though...

Hoping to show this working in a talk tomorrow so any assistance much appreciated! 😀

**Comment by g-ortuno** [comment]
In the future please open a bug at [http://crbug.com/new](http://crbug.com/new).

Would it be possible to get some logs from android?

https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs
