### ISSUE TITLE
Reorder StartNotifications steps

### ISSUE THREAD

**Issue by dati91** [WebBluetoothCG/web-bluetooth#341]
https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattcharacteristic-startnotifications
Currently the connection check (Step 6.) is behind the represented check (Step 2-3.).
Maybe we can reored this to be consistent with the other functions.

**Comment by jyasskin** [comment]
Oops. Yes, the connection check should be in a consistent place for all algorithms.
