### ISSUE TITLE
Security: require devices to opt-in

### ISSUE THREAD

**Issue by johnmellor** [WebBluetoothCG/web-bluetooth#35]
Most existing Bluetooth devices don't expect untrusted websites to be interacting with them. The use cases document [mentions that](http://webbluetoothcg.github.io/web-bluetooth/use-cases.html#secprvreq_protocol_restriction) "a mechanism similar to the [GPU Blacklist](https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists) may be appropriate". However there is many orders of magnitude more variety in bluetooth devices than there is in GPUs, so it seems infeasible to blacklist vulnerable devices. Instead, it might be wise to require devices to opt in to being accessible via the web API.

On the other hand, native apps on all major OSes already get unrestricted access to bluetooth with barely any prompting. So maybe we're already doomed :-(

**Comment by jyasskin** [comment]
I wrote https://medium.com/@jyasskin/the-web-bluetooth-security-model-666b4e7eed2 to analyze the security risks with the new API. Not everyone has been convinced that this is safe enough to expose to the web, but we seem to have general agreement from Chrome's security team that our defenses are enough.
