### ISSUE TITLE
Modify the step numbering of "revoke Bluetooth access"

### ISSUE THREAD

**Issue by zakorgy** [WebBluetoothCG/web-bluetooth#356]
Step 2.3 and 2.4 in [revoke Bluetooth access](https://webbluetoothcg.github.io/web-bluetooth/#revoke-bluetooth-access) steps depends on Step 2.2. Should not be these substeps of Step 2.2 rather than subsequent steps?

**Comment by jyasskin** [comment]
2.2, "Otherwise, detach deviceObj from its device by running the remaining steps." could be removed entirely: it's just a comment saying what meaning the remaining steps have. Unless you see multiple possible interpretations, I don't really think it's worth changing.
