### ISSUE TITLE
No popup to choose device

### ISSUE THREAD

**Issue by majaybabu** [WebBluetoothCG/web-bluetooth#358]
Is it possible to directly connect to a peripheral without having the user choose the peripheral and click on 'pair' ?

**Comment by g-ortuno** [comment]
No. Any time you want to connect to a device we will show the chooser. What use case did you have in mind?

**Comment by majaybabu** [comment]
Reduce friction for user for e.g  when he is trying to make a payment on a merchant site and checkout. Connect to the device running GATT server with no 'device chooser popup' to get payment credentials. Want to remove friction around multiple clicks for the user on browser - 1. Click on a device 2. Click on Pair.

**Comment by majaybabu** [comment]
Is this possible - Scan for devices and connect directly if there is only one device in the scan result. Without having the user choose that one device and pair - Can this feature be provided as an option ?

**Comment by g-ortuno** [comment]
If we were to allowed that then any malicious site could connect any device around users.

**Comment by thegecko** [comment]
There is of course the referring device from physical web

**Comment by majaybabu** [comment]
Is it possible to customize the device chooser  - Change the text from 'wants to pair' to any other customized message and instead of 2 clicks on the chooser to just one click to start pairing.

**Comment by majaybabu** [comment]
@thegecko 
Is it possible for the chrome running on OS X to scan for Eddystone URL beacon and then connect to  it using navigator.bluetooth.referringDevice ?  Any examples would really help.

**Comment by jyasskin** [comment]
`referringDevice` isn't implemented yet, and when it is, that'll be user-directed scans, not page-directed scans. There will be a [scanning API](https://webbluetoothcg.github.io/web-bluetooth/scanning.html), but again, to communicate with a discovered device will take 2 permission prompts.

Chrome requires the two clicks from `requestDevice()` because it's pretty dangerous for users to grant access to a BT device, and we want to give them as much chance as possible to realize what they're doing. Even this level of concern still worries some people: http://www.tomshardware.com/news/google-web-bluetooth-webusb-apis,33589.html. However, another browser could certainly decide to use a different UI that lets the user select the first matching device with a single click.

**Comment by tigoe** [comment]
If we can't replace it with a custom chooser, would it be possible to make the device chooser conform to WCAG 2.0 guidelines? It doesn't currently work too well with a screen reader.

**Comment by reillyeon** [comment]
@tigoe if you are having trouble using Chromium's chooser with a screen reader can you file a bug with details on crbug.com?

**Comment by tigoe** [comment]
Will do. Though I assume web-bluetooth ever gets adopted by other browsers, this will be an API issue, not a browser issue, won't it? Ultimately developers will need to be able to customize all of the UI, including the chooser.

**Comment by jyasskin** [comment]
As long as each browser's UI is accessible, accessibility won't require developers to customize it.

**Comment by tigoe** [comment]
I haven't found the problem to be that tidy in my experience. Different
users have a wide range abilities and disabilities, and customization is
more often than not necessary. Disabilities don't scale well.

But I get your point. I'll seek a solution other than. Web-bluetooth.

**Comment by VagrantZXC** [comment]
I saw the latest GATT Communication API list as:
<img width="826" alt="Screen Shot 2020-05-22 at 2 26 05 PM" src="https://user-images.githubusercontent.com/10545093/82638003-81eb3b00-9c38-11ea-9b6c-2c69ec5ff435.png">
And the status of Chooser UI is yes, does it mean we can customize the Chooser UI now?

**Comment by reillyeon** [comment]
No, we have no plans to make the chooser UI customizable. The API status simply means that the chooser UI is implemented.

**Comment by sbahmani** [comment]
Can I filter list with device id?
