### ISSUE TITLE
no API to do setCharacteristicNotification

### ISSUE THREAD

**Issue by bing-mao** [WebBluetoothCG/web-bluetooth#360]
I'm using a BLE-UART device, want to set one characteristic to notify enabled, but I can not find API like setCharacteristicNotification in android, if I don't set it to notify enabled, call to characteristic.startNotifications will fail.

**Comment by jyasskin** [comment]
Calling startNotifications() is required to enable notifications using the CCCD. If it doesn't in some browser, please file a bug against that browser. For example, Chrome bugs are filed with https://crbug.com/new.
