### ISSUE TITLE
Show chooser without user gesture?

### ISSUE THREAD

**Issue by ThmsD** [WebBluetoothCG/web-bluetooth#364]
Is it possible to show the chooser without a user gesture?
I want to show the chooser after a page has load. (Someone is filling in a form and clicks submit. This loads a new page where the chooser should show up.)

**Comment by beaufortfrancois** [comment]
Hello!

Bluetooth chooser requires a user gesture for security purposes. There is no way to bypass this.
You may want to load your new page inside your webpage if possible.
