### ISSUE TITLE
Allow websites to reconnect to devices already paired

### ISSUE THREAD

**Issue by cholewa1992** [WebBluetoothCG/web-bluetooth#365]
Consider this example:
A web app used a bluetooth peripheral device when ever visited. With the current API the user will have to interact and select the device every time the web app is visited. This is a usability hassle as the user will have to open the paring menu and select the device every time the site is visited.

It is possible to include a feature such that devices already known can be used without having to select them from the paring dropdown?

**Comment by g-ortuno** [comment]
The feature is already included in the spec, see [Permission API Integration](https://webbluetoothcg.github.io/web-bluetooth/#example-permission-api-query). But it hasn't been implemented in Chrome yet. See [Implementation Status](https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md#gatt-communication-api).
