### ISSUE TITLE
How to tell which device is the correct device when they all have the same name

### ISSUE THREAD

**Issue by whatsthebeef** [WebBluetoothCG/web-bluetooth#366]
We currently use the chrome.bluetooth API on Chrome OS to discover our nearby BLE devices and at the same time retrieve RSSI information on these devices. This allows us to indicate to the user which is the closest device without the need for a pairing or a connection. 

Given that all our devices have the same name, there more than likely will be multiple devices operating within discoverable distance and the security restrictions with Web Bluetooth which, as I understand require the user to select (pair) the relevant devices from the list before viewing the RSSI information, how can the user know they are selecting the correct (closest) device without pairing with all devices.

My initial thought was that there could be a RSSI filter attribute on requestDevice on requestLEScan but given the current approach to security this may be a vulnerability as well.

This issue is more pertinent to us now given issues being raised against Chrome OS are being directed to Web Bluetooth as the new solution.

Apologies if I am missing something obvious. I assume this an issue which other products will have.

**Comment by g-ortuno** [comment]
We recognized this use case as well so now Chrome shows an RSSI indicator next to each device in the Device chooser:

![image](https://cloud.githubusercontent.com/assets/3117611/25776611/4b09ba38-3306-11e7-9b7d-281cd7d63127.png)

There is also the [Web Bluetooth Scanning API](https://webbluetoothcg.github.io/web-bluetooth/scanning.html), which hasn't been implemented yet, which would allow developers to receive devices' RSSI.

**Comment by g-ortuno** [comment]
Closing since this seems to solve your problem. Feel free to re-open if it doesn't.

**Comment by antoinegilles** [comment]
i open the subject, is there a method wich can calculate the RSSI in javascript ?

**Comment by batuhanarslan** [comment]
The OS can recognize the RSSI before connecting to device and shows us the indicator. Is there any way to obtain this RSSI value before connecting to device aim to connect the true device?
