### ISSUE TITLE
TypeError: server.getPrimaryService is not a function

### ISSUE THREAD

**Issue by brave2016** [WebBluetoothCG/web-bluetooth#369]
navigator.bluetooth.requestDevice(options).then(device => {
			console.log('Got device:', device.name);
			console.log('id:', device.id);
			console.log('Connected:' + device.gatt.connected);
			console.log('Connected:' + device.gatt.connected);
			document.getElementById("demo").innerHTML="My First JavaScript"+device.name;
		//	bltr =device.gatt.connect();
		          return device;
			}).then(device => {
				document.getElementById("conn").innerHTML="true";
			    return device.gatt.connect;
			}).then(server => {
				document.getElementById("service").innerHTML="trurservcice";
			 server.getPrimaryService('00000000-0000-1000-8000-00805F9B34FB');
			}).then(service => {
	
	              service.getCharacteristic('00000002-0000-1000-8000-00805F9B34FB');
             })
			
			.catch(error => {
			document.getElementById("demo").innerHTML="error"+error;
			});

**Comment by g-ortuno** [comment]
The second arrow function is not returning a promise.

Instead of:
```js
return device.gatt.connect;
```
it should be:
```js
return device.gatt.connect();
```
