### ISSUE TITLE
 it not showing while scanning printer device in Chrome android mobile

### ISSUE THREAD

**Issue by dineshvasan** [WebBluetoothCG/web-bluetooth#375]
This is for sample example  ( https://dineshvasan.github.io/test/)
 i have written for connecting bluetooth device for printing the text but it is not working. kindly check it whether i have made mistake in that code . kindly give me working solution for web bluetooth using service worker. i have referred  all the website but it not working properly.

As per my requirement to access the web bluetooth print the text using service worker.
Kindly do the Needful 
Printer Name : Epson
Printer Model : Epson TM-P20 
`
![20170821_153048](https://user-images.githubusercontent.com/31005845/29514442-2e1defba-8686-11e7-9b4a-e6a5a9b56b8e.jpg)

![20170821_153102](https://user-images.githubusercontent.com/31005845/29514448-359d6446-8686-11e7-814c-081c7fb40a03.jpg)
`

**Comment by beaufortfrancois** [comment]
Can you share some logs?
What do you see?

**Comment by dineshvasan** [comment]
I have shared log file.kindly find the attachment .

Kindly give me working sample of web bluetooth

[btmon.btsnoop.tar.gz](https://github.com/WebBluetoothCG/web-bluetooth/files/1248195/btmon.btsnoop.tar.gz)

**Comment by dineshvasan** [comment]
Its ok fine. i am searching on my mobile in chrome android os version 6.01  this is that site given below (https://googlechrome.github.io/samples/web-bluetooth/device-info.html?allDevices=true ) even not finding another mobile device in Android chrome browser what that exact problem ...

**Comment by dineshvasan** [comment]
Kindly give me a working solution buddy and i am waiting for your response because i have

**Comment by beaufortfrancois** [comment]
Here it is: https://groups.google.com/a/chromium.org/forum/#!topic/web-bluetooth/X26-_58ykVQ
