### ISSUE TITLE
Can not detect Bluetooth device with requestDevice.

### ISSUE THREAD

**Issue by goldingdamien** [WebBluetoothCG/web-bluetooth#388]
I have tried navigator.bluetooth.requestDevice(options) with options = {acceptAllDevices: true} and using the name in filters against a new Bluetooth phone(Bluetooth 4+) and an older device which both are fine at pairing with my computer. 

I have tried following the guides for a solution but everything seems to result in the scanning overlay being shown and it never finding anything. 

I have tried using Chrome Canary, an onclick event, and using https. 

I have also tried the below, and nothing is shown.
chrome://bluetooth-internals/#devices

I just want to be able to test the Bluetooth functionality, so any way of getting this working would be much appreciated, thank you.

**Comment by GraxMonzo** [comment]
Same issue

**Comment by Guziq** [comment]
Interesting, now I have to enable `chrome://flags/#enable-experimental-web-platform-features` on MacOS (that wasn't a case previously).

**Comment by reillyeon** [comment]
Closing this issue as OP has not provided information on what platform they are using. Note that as of Chrome 70 Windows is now fully supported and so this may have fixed your problem.

**Comment by piyush2cloud** [comment]
@reillyeon Can u please help me with how to get heart rate from Fitbit Versa device using BLE,GATT.
