### ISSUE TITLE
navigator.bluetooth not working in typescript

### ISSUE THREAD

**Issue by joaoeudes7** [WebBluetoothCG/web-bluetooth#405]
I am trying to make the chrome bluetooth API call and I am not getting success via typescript. I've already tried applying a file in html () but also to no avail. But if you copy the code and paste it into the browser console, the code runs perfectly :(

In StackOverflow: https://stackoverflow.com/questions/51392146/navigator-bluetooth-not-working-in-typescript

**Comment by reillyeon** [comment]
This is not the right forum for asking for support using the Web Bluetooth API. I'll post an answer on StackOverflow.
