### ISSUE TITLE
"This feature is non-standard and is not on a standards track". Is this accurate?

### ISSUE THREAD

**Issue by timoxley** [WebBluetoothCG/web-bluetooth#406]
The [`Bluetooth` page on MDN ](https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth) says:

> This feature is non-standard and is not on a standards track

![image](https://user-images.githubusercontent.com/43438/43184722-25455b1c-901c-11e8-8827-8b485eba4222.png)

Is this (still) accurate? It appears the warning should perhaps be upgraded to [Experimental](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Conventions_definitions#Experimental)?

![image](https://user-images.githubusercontent.com/43438/43184782-5a9ea66a-901c-11e8-8159-00ca3471eb6e.png)

**Comment by beaufortfrancois** [comment]
@jpmedley may know what is the appropriate wording there.

**Comment by beaufortfrancois** [comment]
Thank you @timoxley for raising this issue.

**Comment by ExE-Boss** [comment]
I’ve done this as part of mdn/browser-compat-data#2609 and mdn/browser-compat-data#2611.

**Comment by jpmedley** [comment]
The latter is correct. Thanks for fixing.

**Comment by timoxley** [comment]
I believe this can be closed, the status messages on all the MDN pages I checked appear to be up to date.
