### ISSUE TITLE
Reconnect to saved device

### ISSUE THREAD

**Issue by Pablotis** [WebBluetoothCG/web-bluetooth#411]
I'm trying to reconnect to a device which was previously selected by user knowing its ID. The current method requestDevice() always shows the chrome interface, I need to save devices (their IDs at least) and attempt to connect to them without the user having to select each one every time. I don't know if that's currently possible.
Thanks

**Comment by beaufortfrancois** [comment]
The Permissions API integation is spec'ed at https://webbluetoothcg.github.io/web-bluetooth/#permission-api-integration but not yet implemented in Chrome.
Once it is, you'll be able to reconnect seamlessly to a "saved" bluetooth device.
