### ISSUE TITLE
No devices detected

### ISSUE THREAD

**Issue by alj8** [WebBluetoothCG/web-bluetooth#412]
I tried the following samples, to be able to get device Information from by BLE device. 
https://googlechrome.github.io/samples/web-bluetooth/device-info.html
https://googlechrome.github.io/samples/web-bluetooth/device-info-async-await.html

The problem is, that no devices are detected, not my intended BLE device, but also not any other devices. Other BLE scanners are able to detect my device, therefore it should not be an issue on that part. 

The chrome flag #enable-experimental-web-platform-features is enabled, and according to different documentations, this should be enough to work fine. 

Am I missing something? Is there anything else I need to change?

Specifications:
OS: Windows 10
Browser: Chrome, Version 70
Device: BLE Robot

Thank you for any help! I would really appreciate it.

**Comment by g-ortuno** [comment]
Please open an issue on [crbug.com/new](https://crbug.com/new). Ideally it would include logs; instructions are [here](https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs). Also what do you see when going to chrome://bluetooth-internals/#devices and starting a scan?
