### ISSUE TITLE
Can't find any device

### ISSUE THREAD

**Issue by helloWorldHitech** [WebBluetoothCG/web-bluetooth#413]
I Can't find any device on windows 10.0.17134
Version 70.0.3538.77 (Official Build) (64-bit)
or Chrome canary
reproduced by https://support.google.com/chrome/answer/6362090?p=bluetooth&visit_id=636766100063628355-1760306673&rd=1
shouldn't it work out of the box for these versions?
It works for the same website via chrome 70 on android

**Comment by g-ortuno** [comment]
This is a repo for the Web Bluetooth spec and it seems you are having trouble with the Chrome's implementation of the spec.

Please open an issue on [crbug.com/new](https://crbug.com/new) (Chrome's bug tracker). Ideally it would include information about your machine e.g. what BT adapter you're using and logs; instructions are [here](https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs). Also a screenshot of what you seen when going to chrome://bluetooth-internals/#adapter and chrome://bluetooth-internals/#devices and starting a scan?
