### ISSUE TITLE
Device Name from scan response

### ISSUE THREAD

**Issue by asaf2208** [WebBluetoothCG/web-bluetooth#414]
I'm working with a ble device that doesn't put his name in the advertisment but instead in the scan response, when i'm using the requestDevice with accept all devices on, the name of my device in windows 10 is always - "Unkown or unsupported device" , but in mac when I do the same thing it does get it's name from the device.

Is there any way to get the device name from the scan response before connecting to it or make it working the same in windows 10 as it does in mac?

**Comment by g-ortuno** [comment]
This is a repo for the Web Bluetooth spec and it seems you are having trouble with Chrome's implementation of the spec.

Please open an issue on [crbug.com/new](https://crbug.com/new) (Chrome's bug tracker).
