### ISSUE TITLE
gatt.connect() API is non-responsive if bluetooth device is connected from laptop thru bluetooth setting (in Mac OS-10.14) 

### ISSUE THREAD

**Issue by Asit-Swain-Mindtree** [WebBluetoothCG/web-bluetooth#432]
I am using web bluetooth to read sensors data from headset. It works perfectly fine as it does BLE connection to headset and read characteristics from GATT services.

When using web BT to read sensor data, i need to play audio over bluetooth. To play Audio over bluetooth, i make classic Bluetooth connection from laptop thru bluetooth setting. Once classic BT connection happens, gatt.connect() api is non-responsive. My question is how to play audio using bluetooth while using web bluetooth for GATT characteristics.

**Comment by reillyeon** [comment]
This is not a spec issue. Please file a bug report against the browser you are using (Chrome or Microsoft Edge).
