### ISSUE TITLE
disconnect not working on windows chrome

### ISSUE THREAD

**Issue by 2524user** [WebBluetoothCG/web-bluetooth#440]
Not disconnected when calling diconnect without calling stopNotifications on Windows version of chrome.(e.g reload page while receiving notification)

**Comment by 2524user** [comment]
Is this commit relevant?
https://chromium.googlesource.com/chromium/src/+/56fb252f0f813a126596aed8be5c70998a2e05b3%5E!

**Comment by 2524user** [comment]
sorry, url is wrong.
https://chromium.googlesource.com/chromium/src/+/56fb252f0f813a126596aed8be5c70998a2e05b3

**Comment by beaufortfrancois** [comment]
@reillyeon may be able to help

**Comment by reillyeon** [comment]
Please file a report on bugs.chromium.org with example code and step-by-step instructions for reproducing this issue. If this appears to be a regression please include the last version in which it worked as expected.

Closing this issue as it is implementation-specific.
