### ISSUE TITLE
Packets loss on macOS

### ISSUE THREAD

**Issue by Installka** [WebBluetoothCG/web-bluetooth#447]
I use Web Bluetooth API to work with accelerometer via Bluetooth module. It's working with sampling rate of 100 Hz.
On Windows 10 everything is OK on any device with any Bluetooth module.
But on macOS every second half of packets goes somewhere. So it's only 50 packets/s, while it should be 100.

I tested it on two MacBooks (Pro 13' w/o Touch Bar 2016, macOS 10.14.5 and 12' 2015; macOS 10.14.4/10.14.5) in Chrome 75, 70, Edge 77. Results are the same.
Also, I tested it on MacBook Pro 17' 2011 (macOS 10.13.6) with BLE 4.0 USB dongle and everything is fine, like on Windows. So, probably, it is the problem in the embedded module. I tried to use this dongle on both of Pro 13' and 12' MacBooks via Apple USB-C to USB Adapter and Web Bluetooth API failed to connect to GATT Server every time.

Also, data receiving graph shows that all the data have been received:
![photo_2019-07-05 16 02 33](https://user-images.githubusercontent.com/26421878/60724257-93ebbe80-9f3e-11e9-903b-66c39ac61ff1.jpeg)

It should receive approximately 100 Hz * 2 bytes * 6 numbers (100 packets/s) + 500 bytes (message header) ≈ 1700 bytes/s. So this almost predicted speed. But when I check data or packets log it's only 50 packets.

What could be the problem?

**Comment by odejesush** [comment]
Hi Installka,

This seems to be an issue with the implementation of Web Bluetooth in Chrome and not an issue with the specification. Browser specific issues should be filed in their respective issue trackers. Please see https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs for instructions on how to file a Web Bluetooth bug for Chrome.
