### ISSUE TITLE
why no bluetooth "classic" (2.0/3.0)

### ISSUE THREAD

**Issue by jgroc-de** [WebBluetoothCG/web-bluetooth#460]
Everything is in the title: i was trying to play with the api and sadly, i can not discover some device which are to old or still using bluetooth 2.0 like some classic bluetooth module for arduino. Yes i can buy ble module but i wonder why this choice? Is it hard? (could be)

**Comment by odejesush** [comment]
Yes, adding Bluetooth Classic is complicated because it is a completely disjoint API from BLE.

**Comment by odejesush** [comment]
I'll add a note to the spec and explainer somewhere as to why there isn't Bluetooth Classic support.

**Comment by jgroc-de** [comment]
thx
