### ISSUE TITLE
Why does the Web Bluetooth Pairing Screen Show Multiple Entries for the Same Device?

### ISSUE THREAD

**Issue by mduffy215** [WebBluetoothCG/web-bluetooth#462]
When my web application goes to pair with my Android device, I get multiple entries for the same device on the pairing screen.

Any ideas why?

![image](https://user-images.githubusercontent.com/8658447/68534080-06f2b080-02f6-11ea-84ea-d1bddcefeca2.png)

Thx!

**Comment by mduffy215** [comment]
Also,  where do the values in the parenthesis come from?

**Comment by reillyeon** [comment]
The value in parentheses is the device's MAC address or a placeholder for it. Your device may be rotating its MAC address while advertising. This is a common privacy feature on mobile devices.

This is not a Web Bluetooth specification issue, but a Chromium issue. According to our issue template please file an issue on crbug.com in the "Blink>Bluetooth" component.

**Comment by mduffy215** [comment]
Thx Reilly.
