### ISSUE TITLE
Rephrase "triggered by user activation" to match the new user activation model

### ISSUE THREAD

**Issue by mustaqahmed** [WebBluetoothCG/web-bluetooth#463]
We have User Activation v2 model [in the HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#tracking-user-activation) now.  "Triggered by user activation" should now be changed accordingly.  See the HTML issue mentioned below.

**Comment by odejesush** [comment]
Would the user activation for this API (and other device APIs like [WebUSB](https://github.com/WICG/webusb/issues/178)) require a transient user activation?

**Comment by reillyeon** [comment]
In Chromium the implementations of both WebUSB and Web Bluetooth require transient activation and do not consume the activation.

**Comment by mustaqahmed** [comment]
FYI: One possibility is that WebUSB and WebBluetooth would rely on user activation [indirectly](https://github.com/w3c/permissions/issues/194#issuecomment-564602997) through Permissions API.  Please consider commenting on that Permissions issue, whether the idea sounds reasonable or bad.
