### ISSUE TITLE
Allow Filtering by Device MAC address when Connecting?

### ISSUE THREAD

**Issue by sciberus** [WebBluetoothCG/web-bluetooth#465]
Has there been any consideration to expanding the Filter options to include the ability to pass in a device's MAC address?  Every device has this unique identifier and it's already passed along with the advertising packet.  Right now, it seems that we are limited to services, device names and Manufacturer data.  However, in a crowed environment with duplicate sensors, it's a bit of a nightmare to control what device you are connecting with.

From a security perspective this would be nice to have as well, as you could prevent your machine from connection to devices you have not essentially white listed.

**Comment by reillyeon** [comment]
This has been previously discussed in #417.
