### ISSUE TITLE
addEventListener working in windows but not working in android chrome

### ISSUE THREAD

**Issue by nemeros111** [WebBluetoothCG/web-bluetooth#468]
My code working fine in Windows 10, Chrome.
But its not working in android 7.1.1 Chrome.

In windows 10: Press connect button > pair > get data success
In Android: Press connect button > pair > cannot get data
But i did follow that: Press connect button > pair > press connect button > pair > get data success.

I have to same press connect and pair twice to get data in Android.

This is device im using: NISSEI MT-500BT  ( http://www.nissei-kk.co.jp/english/medical/thermometer/ )
I had checked chrome://device-log but nothing was stored.

I had recorded a video in two case: PC chrome and Android chrome.
Please check it:

https://www.youtube.com/watch?v=atv4lUJAIUc&feature=share&fbclid=IwAR3DlNPOWgLsDYPQkIHZmQ2dVVjzxM4GTHDzg2Nn_mEfMtwFrgKla6jgwOM

Can anyone help me?

**Comment by reillyeon** [comment]
This looks like a Chromium issue, not a Web Bluetooth specification issue. Please file an issue report on crbug.com and include any sample code you are using to reproduce the problem.
