### ISSUE TITLE
Bluetooth low energy (BLE, navigator.bluetooth.requestLEScan) not working on windows 10

### ISSUE THREAD

**Issue by kzmKZuzmo** [WebBluetoothCG/web-bluetooth#483]
Hello hello, I'm trying to create an application to scan the  bluetooth device , especially on windows and android ,  my simple code 

` navigator.bluetooth.requestLEScan({
            keepRepeatedDevices: true,
            acceptAllAdvertisements: true
        }).then(() => {
            navigator.bluetooth.addEventListener('advertisementreceived', event => {
                console.log("data", event )
            });
        })`
or https://googlechrome.github.io/samples/web-bluetooth/scan.html
 it works everywhere on an android (chrome browser),  macbook (chrome browser) , but windows (chrome browser) it doesn't work on windows, how can i fix or can you help me ?  because windows , android  is important to me

**Comment by odejesush** [comment]
Hi zsmKZuzmo,

This repo is only for issues regarding the Web Bluetooth API specification. This is an issue with Chrome's implementation and should have been filed at https://crbug.com.

The implementation status for this API can be checked [here](https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md#scanning-api) and in the Chromium [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=897312). Only Android and macOS support the Scanning API.
