### ISSUE TITLE
Typo in example-getAvailability-PermissionStatus-onchange 

### ISSUE THREAD

**Issue by Totati** [WebBluetoothCG/web-bluetooth#495]
The [`#example-getAvailability-PermissionStatus-onchange`](https://github.com/WebBluetoothCG/web-bluetooth/blob/16d2ef99aed9fd4a8a349fff470b05c6e1a31121/index.bs#L1851)  is not working when copy pasted, because the `navigator.permissions` is misspelled.

**Comment by odejesush** [comment]
Just an FYI, Web Bluetooth Permissions API integration is not implemented in any browser as of today, so that example will not work properly.
