### ISSUE TITLE
Support for BLE on iOS or WASM

### ISSUE THREAD

**Issue by realrk69** [WebBluetoothCG/web-bluetooth#498]
Hi, I'm a full stack developer working with Django and Vue js. I love web bluetooth and integrate it for all BLE projects, as well as recommended it to my clients. Recently, I got some requests from clients to develop a cross platform app which can run on iOS, Android, Mac OS, Windows and Ubuntu. While all os can run the web app via chrome very well, iOS is the only exception.

I'm confused as to why this is happening. Is it because Apple will lose revenue in the app store or because of security risks? Whatever the case, should I use Flutter (am learning it), WASM (Blazor) or Web stack for cross platform BLE libraries. My objective is to develop a PWA or app which works well on all devices. Client doesn't care if it runs on the web or desktop, a native app or PWA etc. He just wants to see it deployed. (PS: Client is running iot based home automation and lighting control systems, so I need BLE in addition to notifications access).

Sorry for the long question, but I hope you can understand my predicament and guide me.

Side question: Will browser APIs always be dependent on JS ie. will wasm ever not rely completely on JS to access native features?

**Comment by reillyeon** [comment]
Apple's feature dashboard for WebKit lists the status for Web Bluetooth as "[Not Considering](https://webkit.org/status/#feature-web-bluetooth)". There are however a number of options for getting Web Bluetooth on iOS devices. The WebBle app is available on the [App Store](https://apps.apple.com/us/app/webble/id1193531073) and provides a minimal web browser with a Web Bluetooth implementation. The app itself is [open source](https://github.com/daphtdazz/WebBLE). There are also Cordova/PhoneGap plugins which implement a subset of the Web Bluetooth API but they appear unmaintained.

Apple is not a member of this Community Group and so the best way to reach out to them with Safari feature requests is through bugreport.apple.com.

To answer your side question, there is ongoing work, such as the [interface-types](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md) proposal which could allow direct bindings between browser APIs and WASM.
