### ISSUE TITLE
Consider Object.observe for service and nearby-device changes

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#50]
@slightlyoff pointed out that we might be able to use `Object.observe` instead of events to track changes to various bits of Bluetooth metadata. For example, if we define `BluetoothDevice.prototype.services` as the cached array of discovered `BluetoothGattServices`, we could observe it for changes instead of needing to define the [serviceadded, etc. events](https://webbluetoothcg.github.io/web-bluetooth/#service-change-events). We'd need to be clear that this is a cache like `BluetoothGattCharacteristic.value` (#37), rather than an up-front-discovered list of all the services.

Similarly, we could define a `navigator.bluetooth.connectedDevices` array to handle devices getting disconnected and reconnected (#31). That also handles the problem of a re-opened web page finding the devices it already has access to.

**Comment by beaufortfrancois** [comment]
For info, `Object.observe` is going to be deprecated in Chrome 49. See https://esdiscuss.org/topic/an-update-on-object-observe and https://www.chromestatus.com/features/6147094632988672

**Comment by jyasskin** [comment]
Yep, using `Object.observe` is no longer an option.
