### ISSUE TITLE
Same Web BLE code but different behavior between Chrome Desktop and Chrome Mobile

### ISSUE THREAD

**Issue by dngconsulting** [WebBluetoothCG/web-bluetooth#516]
Maybe related to Chromium but probably an issue with the specification or something I miss. Please tell me if you'd prefer I fill a bug in chromium. 

I have the same basic code that issue multiple startNotification() for multiple different characteristics of the same service (or different services). 

``` 
 characteristic1.startNotifications().then(()=>{
        characteristic1.addEventListener('characteristicvaluechanged', event => {
         console.log('Got an Event from CAR 1');
        });
      });

 characteristic2.startNotifications().then(()=>{
        characteristic2.addEventListener('characteristicvaluechanged', event => {
         console.log('Got an Event from CAR 2');
        });
      }); 
```
When I run this code on Chrome Desktop, it works perfectly, I get notifications for both caracs. But when I run it on Chrome Mobile, I get the first notifications for carac 1 and nothing for carac 2. The first wins. It there any known bug on that issue ? 

It is exactly the same chrome version and the same code, only the device type change ...

Thanks for any support

Sami

**Comment by reillyeon** [comment]
Check that the second `startNotifications()` does not generate an error (I see no catch() callback). Some platforms require Bluetooth calls to be sequenced, so issuing a second `startNotifications()` call before the first completes can cause an error.

**Comment by dngconsulting** [comment]
Thanks for your answer. Will check that and tell you if I have any error in the catch statement.  if you have any pointer that would help me to serialize safely startNotifications(), would be appreciated.

Sami

**Comment by reillyeon** [comment]
This is easy to do using async/await. Note that you also don't need to wait for `startNotifications()` to resolve before adding an event listener.

```js
characteristic1.addEventListener('characteristicvaluechanged', event => {
  console.log('Got an Event from CAR 1');
});
characteristic2.addEventListener('characteristicvaluechanged', event => {
  console.log('Got an Event from CAR 2');
});

try {
  await characteristic1.startNotifications();
  await characteristic2.startNotifications();
} catch (e) {
  console.error(`Failed to enable characteristic value change notifications: ${e.message}`);
} 
```

**Comment by dngconsulting** [comment]
@reillyeon I want to thank you a lot for your help and your quick answers. You were right, the startNotifications() should be serialized in order to get the code work on mobile devices. I close the issue.
