### ISSUE TITLE
Bluetooth connection via HID/HSP profiles (Smartphone/PWA to IoT device)

### ISSUE THREAD

**Issue by IoTgenius123** [WebBluetoothCG/web-bluetooth#533]
We are developing an IoT device and face **issues with automatic connectivity** to the smartphone via Bluetooth, as we have to use a PWA instead of a native app. We consider using a **standard profile (**e.g. Headset Profile (HSP), Human Interface Device Profile (HID))  to enable communication via Bluetooth between device and PWA. 

We now require a workaround for the following issue:
**When using HSP/HID, existing connections to the smartphone's hardware (e.g. headset, keyboard) can be interrupted.**

Have you faced similar issues and do you know **workarounds** for this?
Are you knowledgeable about **alternative connection mechanisms** (e.g. NFC, SIM) to connect IoT with PWA incl. pros and cons?

**Comment by reillyeon** [comment]
Apologies for not looking at this issue however it doesn't seem to be relevant to Web Bluetooth as you are using the standard HSP and HID profiles. Web Bluetooth is a good choice for connecting an IoT device with a PWA but requires you to implement GATT services on the peripheral, not the profiles you listed.
