### ISSUE TITLE
should getDevice to get ble macaddress ?

### ISSUE THREAD

**Issue by timgyes123** [WebBluetoothCG/web-bluetooth#537]
what method can get macaddress? In browser if devicename =null will show the mac address
![image](https://user-images.githubusercontent.com/25889534/103875527-843dcf00-510d-11eb-8045-924eb1edce35.png)

 but getDevice and connected can't。 Has any method to do it?

**Comment by reillyeon** [comment]
No, device MAC addresses are intentionally not available through the API. To identify devices use the `BluetoothDevice.id` attribute.
