### ISSUE TITLE
The MDN annotations obscure the view to the text on some window sizes.

### ISSUE THREAD

**Issue by dvmarinoff** [WebBluetoothCG/web-bluetooth#543]
On my laptop noticed that the MDN annotations on the right of the page are hiding the last word in the line.

![webble-issue-1](https://user-images.githubusercontent.com/7523832/114188098-6fade480-9951-11eb-8d8a-665484140382.png)

From the "storeage MUST return a new promise" the word "return" is behind the button.

This changes with window size and happens when window size is:
- between 1247 px and 1350 px
- between  815 px and 1048 px

Also above 1500 px they start hiding on the right because of the appearing horizontal slider.
In fact I didn't notice they existed on my desktop monitor.

Under 768 px they become transparent which kinda solves the issue for smaller mobile devices.

- Chrome Version 89.0.4389.114 (Official Build) (64-bit)
- Ubuntu 20.04.2 LTS
- ThinkPad X240

**Comment by reillyeon** [comment]
I've filed tabatkins/bikeshed#2018 to track this as it isn't specific to the Web Bluetooth specification.
