### ISSUE TITLE
Consider the behavior when multiple applications call requestDevice to scan devices

### ISSUE THREAD

**Issue by shuangMoz** [WebBluetoothCG/web-bluetooth#55]
Is it possible that multiple applications request UA to perform LE scan at the same time? I understand it may depend on OS level, but it will be better to give some implementation suggestions.

**Comment by jyasskin** [comment]
I'd like to allow the UA to run a single discovery for multiple concurrent `requestDevice()` calls, and show the results for each as it gets them.

Currently the spec says that the UA has to run the General or Device Discovery Procedure for each `requestDevice()` call, but it does also say "If the UA has scanned for devices recently … [it] may return the result of that scan". I think that means the UA can do just a single scan for multiple concurrent `requestDevice()` calls.

It does mean that the UA can't be a pure passthrough to several OSes, but it's ok for a spec to require that the UA do work.

Do you have a specific point that you think doesn't work here?

**Comment by Vudentz** [comment]
We have been doing this for quite a long time BlueZ/Linux and we did not encounter any problem, I guess the only difference here is that requestDevice has filters but I don't see why that would create any problem.
