### ISSUE TITLE
Queueing notifications/indications

### ISSUE THREAD

**Issue by JamesB7** [WebBluetoothCG/web-bluetooth#551]
It would be very helpful if the received data from a characteristic change could be on the event as well.
That way, if the value is changing in rapid succession (for example, if a characteristic is used for data transfer, such as the Nordic BLE serial port sample), there's no chance of losing data.
So far, it seems like I haven't lost any data, but Chrome may just be keeping up. Not reassuring. :)
BLE notifications/indications are reliable, and at a hardware level the data *is* sent with the event, so there's no reason to make the upper level API unreliable.

**Comment by dlech** [comment]
As long as you read `characteristicObject.value` in the event callback, there will not be any data loss.

**Comment by reillyeon** [comment]
As David said, this is guaranteed by the specification. The `value` attribute of `BluetoothRemoteGattCharacteristic` will not change until the application returns control back to the Javascript event loop. If the application doesn't want to handle the new value synchronously it can implement its own queuing mechanism.
