### ISSUE TITLE
Can bluetooth objects be used after their originating document is closed?

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#57]
If one document calls `requestDevice()` and gets a `BluetoothDevice`, and then passes that object to another document (through same-origin `iframe` or `window.open`?), does the object stay usable after the originating document is closed? After the originating frame is closed?

What do we need to write in the spec to pin that down?

**Comment by jyasskin** [comment]
Beyond the permission story (where we're going with persistent grants unless someone comes up with an argument otherwise), it's looking like the Chrome implementation is going to have trouble keeping connections open after the originating document/frame/Realm is closed. I'm currently inclined to specify that when the originating document's closed any still-alive objects using that document's global object get disconnected.

@g-ortuno FYI for your implementation patches.

**Comment by beaufortfrancois** [comment]
@jyasskin Does that include potential service workers and web workers?

**Comment by jyasskin** [comment]
@beaufortfrancois I haven't thought about workers yet, but I think that, because you can't assign objects directly into a worker, they won't be affected by this sort of difficulty. [Transfering](https://html.spec.whatwg.org/multipage/infrastructure.html#transferable-objects) objects results in them having the "right" global, so they probably won't be affected by the old global getting close.

**Comment by reillyeon** [comment]
Discussed at 2019 TPAC F2F. Persistent permissions have been specified and are being implemented, which resolves the brunt of this issue. Actual transferring ownership of an object between contexts is technically complex and can be avoided with the use of a shared worker or service worker. Closing this in favor of #422.
