### ISSUE TITLE
Outdated links for Firefox section in readme

### ISSUE THREAD

**Issue by obasille** [WebBluetoothCG/web-bluetooth#580]
The links in the Firefox section of the readme are outdated. 
https://github.com/WebBluetoothCG/web-bluetooth/blob/main/implementation-status.md#firefox

First link references an issue closed 5 years ago.
Second link opens a Bugzilla search which yields 0 issue.

Thank you!

**Comment by beaufortfrancois** [comment]
I've started https://github.com/WebBluetoothCG/web-bluetooth/pull/581 to address this issue. Thank you @obasille!
