### ISSUE TITLE
 requestLEscan not working

### ISSUE THREAD

**Issue by arigus** [WebBluetoothCG/web-bluetooth#590]
scanning ble beacon via requestLEscan on chrome not working anymore. checked official samples. I have an older version of chrome tested it works.

https://googlechrome.github.io/samples/web-bluetooth/scan.html

this sample not working.

with a breakpoint on inspect then step out then ask about allow of listed ble devices, the pressed allow. and works on. but without these steps requestLEScan just hangs. Does any dev encounter this problem?

Most probably: Bluetooth scanning permission prompt automatically closes itself because it makes the page lose focus

Thanks

**Comment by reillyeon** [comment]
This issue is being tracked as [Chromium issue 1323134](https://crbug.com/1323134). Closing this because it isn't a specification issue.
