### ISSUE TITLE
Web Bluetooth Manufacturer Specific Data Map empty

### ISSUE THREAD

**Issue by eskalVAR** [WebBluetoothCG/web-bluetooth#598]
Hello I’m trying to receive manufacturer specific data. I filter by prefix and company id into navigator.requestDevice. 

When running device.watchAdvertisements the event for advertisement received gets fired but there the manufacturer specific data map is empty. 

Is this perhaps due to a permission issue I’m not understanding? The data shows up just fine on internal browser tools.

**Comment by dlech** [comment]
This sounds like a problem with the implementation rather than with the specification. Please see https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs/ for how to file bugs for Chromium.

**Comment by reillyeon** [comment]
Only data matching the [`optionalManufacturerData`](https://webbluetoothcg.github.io/web-bluetooth/#dom-requestdeviceoptions-optionalmanufacturerdata) parameter to `requestDevice` is included in the advertisement event.

This could be an implementation bug, as this feature isn't stable yet. If you can file a Chromium bug with an example of the code you are running and information about the device (perhaps so we can reproduce it) that would be very helpful.

**Comment by eskalVAR** [comment]
When you say optionalmanufacturerdata. Do you mean

option.manufacturerData with the company ID or

option.optionalManufacturerData

An example of the object would be great

Thanks

**Comment by reillyeon** [comment]
I mean `options.optionalManufacturerData`. I don't think we have an example of this on https://googlechrome.github.io/samples/web-bluetooth.

**Comment by eskalVAR** [comment]
So would something like this be sufficient?

options.filters[0].manufacturerData[0].companyIdentifier

options.optionalManufacturerData[0].manufacturerData[0].companyIdentifier

Those both set.

Or should it be formatted differently?

Thanks

**Comment by beaufortfrancois** [comment]
I think* this example code should work.

```js
const manufacturerId = 0x0001;

await navigator.bluetooth.requestDevice({
  acceptAllDevices: true,
  optionalManufacturerData: [manufacturerId],
});

```

**Comment by eskalVAR** [comment]
Perfect that does work thanks!

Any idea why i can only see the first 2 bytes of the advert?

**Comment by eskalVAR** [comment]
This does the job. Thanks!
