### ISSUE TITLE
Design a way for developers to handle devices that come into range "later"

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/web-bluetooth#6]
http://webbluetoothcg.github.io/web-bluetooth/use-cases.html#usecase_lazy_scale
1. User opens a website that can communicate over Service A
2. Website requests later access to devices talking Service A
3. User approves request. (Check with Privacy if this step is needed.)
4. Optional: User closes website.
5. Device X begins advertising Service A.
6. UA presents a list of websites that could handle Device X, allowing user to choose 0 or more.
7. Chosen website is notified and begins interacting with Device X.

The notification could be an event handler in an open web page, or a mechanism like [registerProtocolHandler](http://www.whatwg.org/specs/web-apps/current-work/#custom-handlers) that opens a new tab with a device ID embedded in the URL, or an event handler in a service worker. The event handlers could receive a `BluetoothDevice` instance, but the URL needs a stringified form, which the page could vivify using a to-be-defined function.

**Comment by reillyeon** [comment]
Discussed at the TPAC 2019 F2F:

* In the case where the page is not closed the website can use the `watchAdvertisements()` method to detect the service announcement.
* In the case where the page is closed we could implement the ability for the site to register for a passive scan (different than `requestLEScan()`) which would fire a service worker event when an advertisement is received. This has been filed as #453.
