### ISSUE TITLE
NavigatorBluetooth can be a partial interface

### ISSUE THREAD

**Issue by foolip** [WebBluetoothCG/web-bluetooth#60]
https://webbluetoothcg.github.io/web-bluetooth/#interface-wiring

The style of the spec in this section is a bit atypical. A section title "Extensions to the Navigator Interface" and a partial interface Navigator would be more in line with other specs:

http://dev.w3.org/csswg/cssom/#extensions-to-the-document-interface
http://dev.w3.org/csswg/cssom-view/#extensions-to-the-element-interface
http://w3c.github.io/webcomponents/spec/shadow/#extensions-to-element-interface

**Comment by jyasskin** [comment]
@g-ortuno pointed out that Chrome's implementation already uses partial interfaces here: https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/modules/bluetooth/NavigatorBluetooth.idl, so I'm going to change both this and {`BluetoothDiscovery`,`BluetoothInteraction`} to partial interfaces.
