### ISSUE TITLE
navigator.bluetooth.requestDevice (opt)   same filter but ios browser bluefy doesn't  work

### ISSUE THREAD

**Issue by hrjAccount** [WebBluetoothCG/web-bluetooth#624]
let filters = isIos ? [
      {
        namePrefix: "YK",
        manufacturerData: [{
          companyIdentifier: 0x09b3,
          dataPrefix: new Uint8Array([0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01]),
          mask: new Uint8Array([0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01])
        }]
      }
    ] : [
      {
        manufacturerData: [{
          companyIdentifier: 0x09b3,
          dataPrefix: new Uint8Array([0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01]),
          mask: new Uint8Array([0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01])
        }]
      },
    ]
    let options = {
      filters: filters,
      optionalServices: [Code.bxlink, Code.fota],
      acceptAllDevices: false,
    }; 

 const device = await navigator.bluetooth.requestDevice(options);
 
 
 chrome 、android can   Search for the specific device
 but ios browser bluefy doesn't  work

**Comment by dlech** [comment]
This repository is about the technical specification, not any implementation. I think you need to contact Bluefy support and report the bug there.
