### ISSUE TITLE
Unable to connect to the device, the error message is as follows

### ISSUE THREAD

**Issue by Branches01** [WebBluetoothCG/web-bluetooth#625]
SecurityError: Origin is not allowed to access the service. Tip: Add the service UUID to 'optionalServices' in requestDevice() options. https://webbluetoothcg.github.io/web-bluetooth/#dom-requestdeviceoptions-optionalservices

**Comment by alvinjiooo** [comment]
Hi, 
Usually we create issues here for spec discussion. If you are  seeing issues for Chromium implementation specifically please file a issue to https://issues.chromium.org/.
