### ISSUE TITLE
The API description in the Use Cases doesn't match the one in the Spec

### ISSUE THREAD

**Issue by g-ortuno** [WebBluetoothCG/web-bluetooth#88]
Spec description: `API to discover and communicate with devices over the Bluetooth 4 wireless standard using the Generic Attribute Profile (GATT).`

Use cases description: `... interface to discover and communicate with devices connected via Bluetooth to the device hosting the implementation.`

**Comment by jyasskin** [comment]
I'm not sure the spec's description should match the use-cases description? The use cases and security requirements came first and drove the decisions in the spec, including the decision to limit to GATT.

**Comment by g-ortuno** [comment]
hmm ok. But I still think the wording in the Use Cases' API description is a bit weird. So I thought the best solution would be to match the spec's description.

**Comment by jyasskin** [comment]
Would it make sense to replace the declarative "The Web Bluetooth API defines an interface to …" with something like "We intend to define an API to …"?

**Comment by g-ortuno** [comment]
So: `We intend to define an API that uses Bluetooth to discover and communicate with devices. This document collects use cases for such an API.`

**Comment by jyasskin** [comment]
Sure, that looks good.
